### ISSUE TITLE
error while deserializing

### ISSUE THREAD

**Issue by ruwentos** [Nivaes/Iso20022Net#9]
I use your code like you described. Whatever class I create with the xsd.exe from an official xsd file. Deserializing always crashes with the same error:

'<Document xmlns='urn:iso:std:iso:20022:tech:xsd:camt.053.001.02'> was not expected.'

Did you experience somewhere the same?

**Comment by andres-gimenez** [comment]
If you create a unit test that replicates the problem and I publish it to you.
